# Generated by Django 5.2.5 on 2025-11-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billtype',
            name='billtype_id',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
