# Generated by Django 5.2.5 on 2025-11-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0002_alter_billtype_billtype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='counter_id',
            field=models.IntegerField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='counter',
            name='counter_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentmode',
            name='mode_id',
            field=models.IntegerField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentmode',
            name='mode_name',
            field=models.CharField(max_length=100),
        ),
    ]
