# Generated by Django 5.2.5 on 2025-11-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0003_alter_counter_counter_id_alter_counter_counter_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billtype',
            name='billtype_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='counter',
            name='counter_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='paymentmode',
            name='mode_id',
            field=models.IntegerField(unique=True),
        ),
    ]
