# Generated by Django 5.2.5 on 2025-11-15 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
