# Generated by Django 5.2.5 on 2025-11-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0009_adminsettings_cashierrestriction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsettings',
            name='theme_color',
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='accent_color',
            field=models.CharField(default='#4a6fa5', max_length=20),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='theme_logo/'),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='primary_color',
            field=models.CharField(default='#2e3b4e', max_length=20),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='sidebar_color',
            field=models.CharField(default='#1f2a38', max_length=20),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
