# Generated by Django 5.2.5 on 2025-11-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0010_remove_adminsettings_theme_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='mode',
            field=models.CharField(default='light', max_length=10),
        ),
    ]
