# Generated by Django 5.2.5 on 2025-11-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0011_adminsettings_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_dashboard', models.BooleanField(default=True)),
                ('allow_billing', models.BooleanField(default=True)),
                ('allow_sales_return', models.BooleanField(default=True)),
                ('allow_products', models.BooleanField(default=True)),
                ('allow_items', models.BooleanField(default=True)),
                ('allow_purchase', models.BooleanField(default=True)),
                ('allow_inventory', models.BooleanField(default=True)),
                ('allow_suppliers', models.BooleanField(default=True)),
                ('allow_config_view', models.BooleanField(default=True)),
                ('allow_barcodes', models.BooleanField(default=True)),
                ('allow_reports', models.BooleanField(default=True)),
                ('allow_logs', models.BooleanField(default=True)),
                ('allow_company', models.BooleanField(default=True)),
                ('allow_customers', models.BooleanField(default=True)),
                ('allow_payments', models.BooleanField(default=True)),
                ('allow_expenses', models.BooleanField(default=True)),
                ('allow_settings', models.BooleanField(default=True)),
            ],
        ),
    ]
