# Generated by Django 5.2.5 on 2025-11-19 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0012_permissionsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_dashboard', models.BooleanField(default=True)),
                ('allow_billing', models.BooleanField(default=True)),
                ('allow_sales_return', models.BooleanField(default=True)),
                ('allow_products', models.BooleanField(default=True)),
                ('allow_items', models.BooleanField(default=True)),
                ('allow_purchase', models.BooleanField(default=True)),
                ('allow_inventory', models.BooleanField(default=True)),
                ('allow_suppliers', models.BooleanField(default=True)),
                ('allow_barcodes', models.BooleanField(default=True)),
                ('allow_customers', models.BooleanField(default=True)),
                ('allow_payments', models.BooleanField(default=True)),
                ('allow_expenses', models.BooleanField(default=True)),
                ('allow_reports', models.BooleanField(default=False)),
                ('allow_logs', models.BooleanField(default=False)),
                ('allow_company', models.BooleanField(default=False)),
                ('allow_settings', models.BooleanField(default=False)),
                ('allow_config_view', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_dashboard', models.BooleanField(default=True)),
                ('allow_billing', models.BooleanField(default=True)),
                ('allow_sales_return', models.BooleanField(default=True)),
                ('allow_products', models.BooleanField(default=True)),
                ('allow_items', models.BooleanField(default=True)),
                ('allow_purchase', models.BooleanField(default=True)),
                ('allow_inventory', models.BooleanField(default=True)),
                ('allow_suppliers', models.BooleanField(default=True)),
                ('allow_barcodes', models.BooleanField(default=True)),
                ('allow_customers', models.BooleanField(default=True)),
                ('allow_payments', models.BooleanField(default=True)),
                ('allow_expenses', models.BooleanField(default=True)),
                ('allow_reports', models.BooleanField(default=True)),
                ('allow_logs', models.BooleanField(default=True)),
                ('allow_company', models.BooleanField(default=True)),
                ('allow_settings', models.BooleanField(default=True)),
                ('allow_config_view', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PermissionSettings',
        ),
    ]
