# Generated by Django 5.2.5 on 2025-11-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0014_alter_cashierpermission_allow_barcodes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mysql_table', models.CharField(max_length=255)),
                ('postgres_table', models.CharField(max_length=255)),
                ('migrated_rows', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('migrated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
