# Generated by Django 5.2.5 on 2025-11-21 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0015_migrationlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='migrationlog',
            old_name='mysql_table',
            new_name='mssql_table',
        ),
    ]
