# Generated by Django 5.2.5 on 2025-11-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0016_rename_mysql_table_migrationlog_mssql_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationlog',
            name='mssql_table',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='migrationlog',
            name='postgres_table',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='migrationlog',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
