# Generated by Django 5.2.5 on 2025-11-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0017_alter_migrationlog_mssql_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationlog',
            name='column_mapping',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='migrationlog',
            name='mssql_table',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='migrationlog',
            name='postgres_table',
            field=models.CharField(max_length=255),
        ),
    ]
