# Generated by Django 5.2.5 on 2025-11-21 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0018_migrationlog_column_mapping_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='migrationlog',
            unique_together={('mssql_table', 'postgres_table')},
        ),
    ]
