# Generated by Django 5.2.5 on 2025-11-21 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0020_alter_migrationlog_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='migrationlog',
            unique_together={('mssql_table', 'postgres_table')},
        ),
    ]
