# Generated by Django 5.2.5 on 2025-11-21 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0021_alter_migrationlog_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='migrationlog',
            unique_together=set(),
        ),
    ]
