# Generated by Django 5.2.5 on 2025-11-22 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0023_alter_supplier_account_number_alter_supplier_address_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='supplier',
            table='MahilMartPOS_App_supplier',
        ),
    ]
