# Generated by Django 5.2.5 on 2025-12-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0025_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
