# Generated by Django 5.2.5 on 2025-12-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0026_alter_activitylog_role_alter_activitylog_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
