# Generated by Django 5.2.5 on 2025-12-26 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0027_customer_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='total_after_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='billing',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='billing',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billings', to='MahilMartPOS_App.customer'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='discount_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
