# Generated by Django 5.2.5 on 2025-12-26 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0028_billing_total_after_discount_billing_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingitem',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='billing',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billing',
            name='received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MahilMartPOS_App.customer'),
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='unit',
            field=models.CharField(max_length=20),
        ),
    ]
