# Generated by Django 5.2.5 on 2025-12-26 08:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0029_billingitem_tax_alter_billing_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='total_after_discount',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='billingitem',
            name='tax',
        ),
        migrations.AlterField(
            model_name='billing',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billing',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MahilMartPOS_App.customer'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='discount_amt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='received',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MahilMartPOS_App.customer'),
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='qty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='unit',
            field=models.CharField(max_length=50),
        ),
    ]
