# Generated by Django 5.2.5 on 2025-12-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0030_remove_billing_total_after_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
