# Generated by Django 5.2.4 on 2025-12-31 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0031_alter_adminsettings_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='commodity',
        ),
        migrations.RemoveField(
            model_name='group',
            name='under',
        ),
        migrations.AddField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='MahilMartPOS_App.group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='alias_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='print_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
