# Generated by Django 5.2.4 on 2026-01-20 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0032_remove_group_commodity_remove_group_under_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('retail', 'Retail'), ('medical', 'Medical Shop'), ('book', 'Book Stall')], max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('edition', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MahilMartPOS_App.item')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt_composition', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('schedule_type', models.CharField(choices=[('OTC', 'OTC'), ('H', 'Schedule H'), ('H1', 'Schedule H1'), ('X', 'Schedule X')], max_length=10)),
                ('prescription_required', models.BooleanField(default=False)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MahilMartPOS_App.item')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MahilMartPOS_App.item')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=255)),
                ('prescription_date', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='prescriptions/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MahilMartPOS_App.customer')),
            ],
        ),
    ]
