# Generated by Django 5.2.4 on 2026-01-20 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0033_businesstype_book_medicine_medicinebatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='business_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='MahilMartPOS_App.businesstype'),
        ),
    ]
