# Generated by Django 5.2.4 on 2026-01-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahilMartPOS_App', '0034_companydetails_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='short_name',
            field=models.CharField(default='MM', help_text='Short store code like MM', max_length=5),
            preserve_default=False,
        ),
    ]
